### ISSUE TITLE
Issues with threading (Found on blanketcon)

### ISSUE THREAD

**Issue by Patbox** [NucleoidMC/substrate#3]
Requires further investigation, ideally all methods should be made safe to use while running on multiple threads.
Stacktrace looks rather vanillish, so this could happen on the server

```
[18:17:34] [Server thread/ERROR]: Error executing task on Chunk source main thread executor for fantasy:boypxzmmzm4bfyd2
net.minecraft.class_148: Exception generating new chunk
	at net.minecraft.class_3898.method_39934(class_3898.java:699) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:564) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:573) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3215.method_19492(class_3215.java:282) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.handler$eib000$carpet$modifiedRunLoop(MinecraftServer.java:18951) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[transformed-mod-minecraft.i0:0/:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList.forEach(ArrayList.java:1598) ~[?:?]
	at net.minecraft.class_6032.method_35088(class_6032.java:45) ~[transformed-mod-minecraft.i0:0/:?]
	at xyz.nucleoid.substrate.gen.GrassGen.generate(GrassGen.java:29) ~[transformed-mod-substrate.i0:0/:?]
	at xyz.nucleoid.bedwars.game.generator.BwSkyChunkGenerator.method_12102(BwSkyChunkGenerator.java:94) ~[transformed-mod-bedwars.i0:0/:?]
	at net.minecraft.class_2806.method_51375(class_2806.java:108) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:309) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_2806.method_12154(class_2806.java:252) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3898.method_17225(class_3898.java:684) ~[transformed-mod-minecraft.i0:0/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:673) ~[transformed-mod-minecraft.i0:0/:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_3846.run(class_3846.java:102) ~[transformed-mod-minecraft.i0:0/:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
```

**Comment by Patbox** [comment]
Same issue was found in both Survival Games and Bedwars, so might be also bug with these two

**Comment by ashhhleyyy** [comment]
Seems to be caused by [this line](https://github.com/NucleoidMC/substrate/blob/1.19/src/main/java/xyz/nucleoid/substrate/gen/GrassGen.java#L29) modifying the list of states with with `WeightedList.shuffle` call. I'm not familiar with the class, but if there is a way to get a random element in the list rather than mutating it, that should fix the CME

**Comment by Patbox** [comment]
Oh thanks for checking! Yeah would be good to look through all of the code and check for similar stuff
